fix: set AWS_ENDPOINT_URL_DEADLINE after installing service model
aws-deadline/deadline-cloud-test-fixtures pull request #96
Opened 2024-04-17 22:23 UTC by jericht

### What was the problem/requirement? (What/Why)
Two issues:
1. With the release of botocore that includes our service model, our method of configuring service model is no longer sufficient to contact endpoints other than the one included in botocore. We need to set`AWS_ENDPOINT_URL_DEADLINE` to tell boto that we want requests to Deadline Cloud to go to a different endpoint.
2. The test fixtures code that copies the service model from the test runner machine to the worker machine does not support gzip files, which is the format that service models included botocore are in.

### What was the solution? (How)
1. Set `AWS_ENDPOINT_URL_DEADLINE` whenever we install a service model
2. Support gzip (`.json.gz`) service model files

### What is the impact of this change?
1. We can contact different Deadline Cloud endpoints for our tests
2. We support gzip service model files

### How was this change tested?
- `hatch build && hatch run test`
- Installed this package into [deadline-cloud-worker-agent](https://github.com/aws-deadline/deadline-cloud-worker-agent) and ran those integration tests (after making [some fixes](https://github.com/aws-deadline/deadline-cloud-worker-agent/pull/297)), verifying they succeed

### Was this change documented?
No

### Is this a breaking change?
Yes

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-04-22 17:12 UTC, moorec-aws approved these changes

2024-04-22 20:08 UTC, jusiskin requested changes

2024-04-22 20:08 UTC, jusiskin commented on src/deadline_test_fixtures/fixtures.py
> +        )
I may have missed it, but do we also need to configure the `AWS_ENDPOINT_URL_DEADLINE` environment variable on the worker?

2024-05-31 19:27 UTC, jericht commented on src/deadline_test_fixtures/fixtures.py
> +        )
Done

2024-06-03 16:58 UTC, jusiskin approved these changes
Approved with understanding that configuring the `AWS_ENDPOINT_URL_DEADLINE` env var on the created workers will be completed before the next release

2024-06-03 17:21 UTC, merged